# why is this bugging on line 10?

def third_greatest(num)
	greatest = nil
	second_greatest = nil
	third_greatest = nil

	num.each do |n|
	    current_number = n
       if (greatest == nil) || (current_number > greatest)
         third_greatest = second_greatest 
         second_greatest = greatest
         greatest = current_number
       elsif (second_greatest == nil) || (current_number > second_greatest) 
       	 third_greatest = second_greatest 
         second_greatest = current_number
       elsif (third_greatest == nil) || (current_number > third_greatest)  
       	 third_greatest = current_number
       end
	end
	third_greatest
end

puts(
  'third_greatest([5, 3, 7]) == 3: ' +
  (third_greatest([5, 3, 7]) == 3).to_s
)
puts(
  'third_greatest([5, 3, 7, 4]) == 4: ' +
  (third_greatest([5, 3, 7, 4]) == 4).to_s
)
puts(
  'third_greatest([2, 3, 7, 4]) == 3: ' +
  (third_greatest([2, 3, 7, 4]) == 3).to_s
)
